"""
Coverage for etl.py, the transform the whole demo rests on and which had none.

etl.py is a script rather than a module: roughly 55 top-level statements run on
import, opening SQLite and writing warehouse/. So it is exercised the way it is
actually used - generated into a throwaway directory and run - rather than by
refactoring working code to make it importable. test_gates.py already shells out
this way for propose_mapping and validate_mapping.

Sources are gitignored and regenerated by generate_sources.py under random.seed(42),
so the figures asserted below are deterministic. Verified: a clean generate in an
empty directory reproduces 7,670 rows x 45 columns and $3,056,034.74 exactly.
"""
import csv
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Figures pinned from a clean seeded run. A change here means the pipeline's output
# moved, which is either a regression or a deliberate change that should be re-pinned.
EXPECTED_ROWS = 7670
EXPECTED_COLS = 45
EXPECTED_ORDERS = 3567
EXPECTED_REVENUE_USD = 3056034.74
EXPECTED_SOURCES = 18
CANONICAL_REGIONS = {"North America", "EMEA", "APAC", "LATAM"}

# margin_usd and cost_usd are rounded independently, so the identity holds to the
# cent rather than exactly - 19 of 7,670 rows land a penny apart.
CENT = 0.011

_pipeline_dir = None


def _run(script, cwd):
    """Runs a pipeline script and returns the completed process (never raises)."""
    return subprocess.run(
        [sys.executable, script], cwd=cwd, capture_output=True, text=True)


def _fresh_sources_dir():
    """A throwaway copy of the pipeline with freshly generated sources."""
    work = tempfile.mkdtemp(prefix="bi-etl-")
    shutil.copytree(os.path.join(REPO, "mapper"), os.path.join(work, "mapper"))
    for name in os.listdir(REPO):
        if name.endswith(".py"):
            shutil.copy(os.path.join(REPO, name), os.path.join(work, name))
    generated = _run("generate_sources.py", work)
    assert generated.returncode == 0, generated.stderr
    return work


def setUpModule():
    """Build and run the pipeline once; every read-only assertion shares it."""
    global _pipeline_dir
    _pipeline_dir = _fresh_sources_dir()
    result = _run("etl.py", _pipeline_dir)
    assert result.returncode == 0, result.stderr


def tearDownModule():
    shutil.rmtree(_pipeline_dir, ignore_errors=True)


def _flat_rows():
    path = os.path.join(_pipeline_dir, "warehouse", "flat_sales.csv")
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _dashboard():
    path = os.path.join(_pipeline_dir, "warehouse", "dashboard_data.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# Iteration lives in helpers so the test bodies stay linear.
def _count_margin_identity_violations(rows):
    return sum(1 for r in rows
               if abs((float(r["revenue_usd"]) - float(r["cost_usd"]))
                      - float(r["margin_usd"])) > CENT)


def _count_cost_identity_violations(rows):
    return sum(1 for r in rows
               if abs(float(r["unit_cost_usd"]) * int(r["qty"])
                      - float(r["cost_usd"])) > CENT)


def _count_non_iso_dates(rows):
    return sum(1 for r in rows
               if len(r["order_date"]) != 10 or r["order_date"][4] != "-")


def _count_blank_keys(rows):
    return sum(1 for r in rows if not r["order_id"] or not r["product_id"])


def _total_revenue(rows):
    return round(sum(float(r["revenue_usd"]) for r in rows), 2)


class TestFlatTableGrain(unittest.TestCase):
    """The join must land on the order-line grain: no fanout, no silent drops."""

    def test_FlatTable_AfterAFullRun_HasTheExactSeededRowAndColumnCount(self):
        rows = _flat_rows()

        actual = (len(rows), len(rows[0]))

        self.assertEqual((EXPECTED_ROWS, EXPECTED_COLS), actual)

    def test_FlatTable_AfterAFullRun_CoversEverySeededOrder(self):
        rows = _flat_rows()

        orders = {r["order_id"] for r in rows}

        self.assertEqual(EXPECTED_ORDERS, len(orders))

    def test_FlatTable_AfterAFullRun_HasNoBlankJoinKeys(self):
        rows = _flat_rows()

        blanks = _count_blank_keys(rows)

        self.assertEqual(0, blanks)

    def test_FlatTable_AfterAFullRun_ExcludesCancelledOrdersEntirely(self):
        rows = _flat_rows()

        statuses = {r["order_status"] for r in rows}

        self.assertNotIn("cancelled", statuses)
        self.assertEqual({"delivered", "processing", "shipped"}, statuses)


class TestFlatTableReconciles(unittest.TestCase):
    """Money must add up. These are the assertions a BI demo actually rests on."""

    def test_TotalRevenue_AfterAFullRun_MatchesTheSeededFigureToTheCent(self):
        rows = _flat_rows()

        total = _total_revenue(rows)

        self.assertEqual(EXPECTED_REVENUE_USD, total)

    def test_CostUsd_ForEveryRow_EqualsUnitCostTimesQuantity(self):
        rows = _flat_rows()

        violations = _count_cost_identity_violations(rows)

        self.assertEqual(0, violations)

    def test_MarginUsd_ForEveryRow_EqualsRevenueMinusCostWithinAPenny(self):
        rows = _flat_rows()

        violations = _count_margin_identity_violations(rows)

        self.assertEqual(0, violations)


class TestConformance(unittest.TestCase):
    """The messy-source conforming the pipeline exists to demonstrate."""

    def test_Region_AfterConforming_UsesOnlyCanonicalNames(self):
        rows = _flat_rows()

        regions = {r["region"] for r in rows}

        self.assertEqual(CANONICAL_REGIONS, regions)

    def test_OrderDate_AfterConforming_IsIsoForEveryRow(self):
        rows = _flat_rows()

        violations = _count_non_iso_dates(rows)

        self.assertEqual(0, violations)


class TestDashboardPayload(unittest.TestCase):
    """The dashboard embed must agree with the flat table it is derived from."""

    def test_DashboardMeta_AfterAFullRun_AgreesWithTheFlatTable(self):
        dash = _dashboard()

        meta = dash["meta"]

        self.assertEqual(EXPECTED_SOURCES, meta["sources"])
        self.assertEqual(EXPECTED_ORDERS, meta["orders"])
        self.assertEqual(EXPECTED_COLS, meta["flat_cols"])

    def test_DashboardRows_AfterAFullRun_MatchTheFlatTableRowForRow(self):
        dash = _dashboard()

        self.assertEqual(EXPECTED_ROWS, len(dash["rows"]))
        self.assertEqual(len(dash["cols"]), len(dash["rows"][0]))

    def test_Lineage_AfterAFullRun_RecordsEverySourceExactlyOnce(self):
        dash = _dashboard()

        files = [entry["file"] for entry in dash["lineage"]]

        self.assertEqual(EXPECTED_SOURCES, len(files))
        self.assertEqual(EXPECTED_SOURCES, len(set(files)))


class TestEtlRejectsBadInput(unittest.TestCase):
    """
    A pipeline that half-succeeds on bad input is worse than one that stops: the
    dashboard renders and the number is quietly wrong. Each case must exit non-zero.
    """

    def setUp(self):
        self.work = _fresh_sources_dir()
        self.addCleanup(shutil.rmtree, self.work, ignore_errors=True)

    def _rewrite_first_customer(self, field, value):
        path = os.path.join(self.work, "sources", "crm_customers.csv")
        with open(path, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        rows[0][field] = value
        with open(path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)

    def test_Etl_WithAnUnmappedRegionCode_FailsLoudlyInsteadOfMiscoding(self):
        self._rewrite_first_customer("region", "MARS")

        result = _run("etl.py", self.work)

        self.assertEqual(1, result.returncode)
        self.assertIn("KeyError", result.stderr)
        self.assertIn("MARS", result.stderr)

    def test_Etl_WithAnUnparseableDate_FailsLoudlyInsteadOfDroppingTheRow(self):
        self._rewrite_first_customer("signup_date", "not-a-date")

        result = _run("etl.py", self.work)

        self.assertEqual(1, result.returncode)
        self.assertIn("ValueError", result.stderr)

    def test_Etl_WithADateInTheWrongSourceFormat_FailsRatherThanMisreadingIt(self):
        # ISO where the CRM exports m/d/Y. Silently accepting it would swap month
        # and day for the first twelve days of any month.
        self._rewrite_first_customer("signup_date", "2026-03-04")

        result = _run("etl.py", self.work)

        self.assertEqual(1, result.returncode)
        self.assertIn("ValueError", result.stderr)

    def test_Etl_WithAMissingSourceFile_FailsInsteadOfEmittingAThinnerTable(self):
        os.remove(os.path.join(self.work, "sources", "fx_rates.csv"))

        result = _run("etl.py", self.work)

        self.assertEqual(1, result.returncode)
        self.assertIn("FileNotFoundError", result.stderr)

    def test_Etl_WithAMissingSourceFile_WritesNoFlatTable(self):
        os.remove(os.path.join(self.work, "sources", "fx_rates.csv"))
        flat = os.path.join(self.work, "warehouse", "flat_sales.csv")

        _run("etl.py", self.work)

        self.assertFalse(os.path.exists(flat))


class TestEtlIsDeterministic(unittest.TestCase):
    """The seed is the contract: the demo has to reproduce the published figures."""

    def test_Etl_RunTwiceOverTheSameSources_ProducesAByteIdenticalFlatTable(self):
        flat = os.path.join(_pipeline_dir, "warehouse", "flat_sales.csv")
        with open(flat, "rb") as f:
            first = f.read()

        rerun = _run("etl.py", _pipeline_dir)

        self.assertEqual(0, rerun.returncode)
        with open(flat, "rb") as f:
            self.assertEqual(first, f.read())


if __name__ == "__main__":
    unittest.main()
